### PR TITLE
feat: upgrade rescript version

### PR DESCRIPTION
**Pull request by DCKT**

### CODE REVIEW

**Review by MoOx — APPROVED** [review]

**Comment by Freddy03h** [comment]
@MoOx what's the strategy for releasing a new version?

**Comment by DCKT** [comment]
This is a personal take but I think we should leave the 1:1 version idea of bindings. 
It's works well when the bindings can be done in one version but for big packages like react-navigation where there are a LOT of options it would obviously could not follow the package version at some point.

It should just at least match the minor version (`1.X`) or be clear in the readme with a table like this : 

| Bindings  | Package |
| ------------- | ------------- |
| 2.X  |  >= 2.X  |
| 1.X  | < 2.X | |

**Comment by Freddy03h** [comment]
@DCKT I find it's usefull to not have to check each time I want to upgrade a package and its binding, for **each** dependencies.

But yes it's not designed  for when you need to make a rescript related update…

**Comment by MoOx** [comment]
I will stick to 1:1 version even if that's breaking for some people.
This bindings are probably used by a niche anyway.

**Comment by MoOx** [comment]
You can check this https://rescript-react-native.github.io/docs/install#note-about-rescript-react-native-version-number

**Comment by Freddy03h** [comment]
@MoOx So you recommend a `4.x.0` version for a rescript upgrade?

**Comment by MoOx** [comment]
Yes ! With proper notice in changelog :)

**Pull request merged**
